apiVersion: v1
kind: Service
metadata:
  name: lin-developer-tools-web-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    app: lin-developer-tools
    type: web-pod
