apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: busybox-pod
    spec:
      containers:
        - name: busybox
          image: busybox
  replicas: 4
  selector:
    matchLabels:
      name: busybox-pod